name: required_environment
channels: 
    - conda-forge
    - underworldcode
dependencies:
    - nb_conda_kernels
    - stripy
    - litho1pt0
    - quagmire
    - cartopy
    - obspy
    - pandas
    - pip
    - libiconv
    - swig
    - scons
    - compilers 
