name: required_environment
channels: 
    - conda-forge
    - underworldcode
dependencies:
    - nb_conda_kernels
    - stripy
    - litho1pt0
    - quagmire
    - cartopy
    - obspy
    - pandas
    - pip
    - libiconv
    - swig>=4.0.0
    - scons
    - compilers 
    - pip:
      - xvfbwrapper
      - lavavu  # the apt-get packages should be sufficient for this to build
      # - underworldcode # needs environment variables to be set - see installer script

